set prof=Danilo
set dis1=Disciplina1
set dis2=Disciplina2
set dis3=Disciplina3
set dis4=Disciplina4
set uni1=Unidade1
set uni2=Unidade2
set uni3=Unidade3
set at=Atividade
set avs=Avaliacoes
set av1=Prova1
set av2=Prova2
set av3=Prova3
set rec=Recuperacao

mkdir %prof%\%dis1%\%uni1%\%at%
mkdir %prof%\%dis1%\%uni2%\%at%
mkdir %prof%\%dis1%\%uni3%\%at%
mkdir %prof%\%dis1%\%avs%\%av1%
mkdir %prof%\%dis1%\%avs%\%av2%
mkdir %prof%\%dis1%\%avs%\%av3%
mkdir %prof%\%dis1%\%avs%\%rec%
mkdir %prof%\%dis2%\%uni1%\%at%
mkdir %prof%\%dis2%\%uni2%\%at%
mkdir %prof%\%dis2%\%uni3%\%at%
mkdir %prof%\%dis2%\%avs%\%av1%
mkdir %prof%\%dis2%\%avs%\%av2%
mkdir %prof%\%dis2%\%avs%\%av3%
mkdir %prof%\%dis2%\%avs%\%rec%
mkdir %prof%\%dis3%\%uni1%\%at%
mkdir %prof%\%dis3%\%uni2%\%at%
mkdir %prof%\%dis3%\%uni3%\%at%
mkdir %prof%\%dis3%\%avs%\%av1%
mkdir %prof%\%dis3%\%avs%\%av2%
mkdir %prof%\%dis3%\%avs%\%av3%
mkdir %prof%\%dis3%\%avs%\%rec%
mkdir %prof%\%dis4%\%uni1%\%at%
mkdir %prof%\%dis4%\%uni2%\%at%
mkdir %prof%\%dis4%\%uni3%\%at%
mkdir %prof%\%dis4%\%avs%\%av1%
mkdir %prof%\%dis4%\%avs%\%av2%
mkdir %prof%\%dis4%\%avs%\%av3%
mkdir %prof%\%dis4%\%avs%\%rec%